In [67]:
# Numerical Methods and Optimization in Finance
install.packages('NMOF')

Installing package into ‘/srv/rlibs’
(as ‘lib’ is unspecified)



In [68]:
set.seed(1345797)

In [69]:
N <- 8

In [70]:
rand_position <- sample.int(N)
rand_position

[1] 6 5 7 2 3 8 1 4

In [71]:
data_frame <- data.frame(row = 1:N , column = rand_position)
data_frame

row column
1 1   6     
2 2   5     
3 3   7     
4 4   2     
5 5   3     
6 6   8     
7 7   1     
8 8   4

In [72]:
chessboard <- function(rand_position, queen = "Q", sep = '  '){
    n <- length(rand_position)
    row <- rep('_', n)
    
    for(i in seq_len(n)){
        row_i <- row
        row_i[rand_position[i]] <- queen
        
        cat(paste(row_i, collapse = sep))
        cat('\n')
    }
}

In [73]:
chessboard(rand_position)

_  _  _  _  _  Q  _  _
_  _  _  _  Q  _  _  _
_  _  _  _  _  _  Q  _
_  Q  _  _  _  _  _  _
_  _  Q  _  _  _  _  _
_  _  _  _  _  _  _  Q
Q  _  _  _  _  _  _  _
_  _  _  Q  _  _  _  _


In [74]:
matrix_diag <- array(NA, dim = c(N,N))
matrix_diag

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] NA   NA   NA   NA   NA   NA   NA   NA  
[2,] NA   NA   NA   NA   NA   NA   NA   NA  
[3,] NA   NA   NA   NA   NA   NA   NA   NA  
[4,] NA   NA   NA   NA   NA   NA   NA   NA  
[5,] NA   NA   NA   NA   NA   NA   NA   NA  
[6,] NA   NA   NA   NA   NA   NA   NA   NA  
[7,] NA   NA   NA   NA   NA   NA   NA   NA  
[8,] NA   NA   NA   NA   NA   NA   NA   NA

In [75]:
for(row in  1:N)
    for(col in 1:N)
        matrix_diag[row,col] <- col - row
    

matrix_diag

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]  0    1    2    3    4    5    6   7   
[2,] -1    0    1    2    3    4    5   6   
[3,] -2   -1    0    1    2    3    4   5   
[4,] -3   -2   -1    0    1    2    3   4   
[5,] -4   -3   -2   -1    0    1    2   3   
[6,] -5   -4   -3   -2   -1    0    1   2   
[7,] -6   -5   -4   -3   -2   -1    0   1   
[8,] -7   -6   -5   -4   -3   -2   -1   0

In [76]:
matrix_rev_diag <- array(NA, dim = c(N,N))
matrix_rev_diag

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] NA   NA   NA   NA   NA   NA   NA   NA  
[2,] NA   NA   NA   NA   NA   NA   NA   NA  
[3,] NA   NA   NA   NA   NA   NA   NA   NA  
[4,] NA   NA   NA   NA   NA   NA   NA   NA  
[5,] NA   NA   NA   NA   NA   NA   NA   NA  
[6,] NA   NA   NA   NA   NA   NA   NA   NA  
[7,] NA   NA   NA   NA   NA   NA   NA   NA  
[8,] NA   NA   NA   NA   NA   NA   NA   NA

In [77]:
for(row in  1:N)
    for(col in 1:N)
        matrix_rev_diag[row,col] <- col + row - (N + 1)
    

matrix_diag

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]  0    1    2    3    4    5    6   7   
[2,] -1    0    1    2    3    4    5   6   
[3,] -2   -1    0    1    2    3    4   5   
[4,] -3   -2   -1    0    1    2    3   4   
[5,] -4   -3   -2   -1    0    1    2   3   
[6,] -5   -4   -3   -2   -1    0    1   2   
[7,] -6   -5   -4   -3   -2   -1    0   1   
[8,] -7   -6   -5   -4   -3   -2   -1   0

In [78]:
rand_position

[1] 6 5 7 2 3 8 1 4

In [79]:
duplicated(rand_position)

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

In [80]:
sum(duplicated(rand_position))

[1] 0

In [81]:
duplicated(rand_position - seq_along(rand_position))

[1] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE

In [82]:
rand_position - seq_along(rand_position)

[1]  5  3  4 -2 -2  2 -6 -4

In [83]:
sum(duplicated(rand_position - seq_along(rand_position)))

[1] 1

In [84]:
duplicated(rand_position + seq_along(rand_position))

[1] FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE

In [85]:
rand_position + seq_along(rand_position)

[1]  7  7 10  6  8 14  8 12

In [86]:
sum(duplicated(rand_position + seq_along(rand_position)))

[1] 2

In [87]:
num_attacks <- function(rand_position){
    sum(duplicated(rand_position))+
    sum(duplicated(rand_position - seq_along(rand_position))) +
    sum(duplicated(rand_position + seq_along(rand_position)))
}

In [88]:
num_attacks(rand_position)

[1] 3

In [89]:
move_one_queen <- function(rand_position){
    step <- 4
    i <- sample.int(N,1)
    
    rand_position[i] <- rand_position[1] +sample(c(1:step, -(1:step)),1)
    
    if(rand_position[i]>N)
        rand_position[i] <- 1
    else if(rand_position[i] < 1)
        rand_position[i] <- N
    
    rand_position
        
}

In [90]:
chessboard(rand_position)

_  _  _  _  _  Q  _  _
_  _  _  _  Q  _  _  _
_  _  _  _  _  _  Q  _
_  Q  _  _  _  _  _  _
_  _  Q  _  _  _  _  _
_  _  _  _  _  _  _  Q
Q  _  _  _  _  _  _  _
_  _  _  Q  _  _  _  _


In [91]:
chessboard(rand_position <- move_one_queen(rand_position))

_  _  _  _  _  Q  _  _
_  _  Q  _  _  _  _  _
_  _  _  _  _  _  Q  _
_  Q  _  _  _  _  _  _
_  _  Q  _  _  _  _  _
_  _  _  _  _  _  _  Q
Q  _  _  _  _  _  _  _
_  _  _  Q  _  _  _  _


In [92]:
chessboard(rand_position <- move_one_queen(rand_position))

_  _  _  _  _  Q  _  _
_  _  Q  _  _  _  _  _
_  _  _  _  _  _  Q  _
_  Q  _  _  _  _  _  _
_  _  Q  _  _  _  _  _
_  _  _  _  _  _  _  Q
_  _  _  _  _  _  Q  _
_  _  _  Q  _  _  _  _


In [93]:
p0 <- rep(2,N)
p0

[1] 2 2 2 2 2 2 2 2

In [94]:
chessboard(p0)

_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _


In [95]:
chessboard(rand_position <- move_one_queen(p0))

_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  _  _  _  _  Q  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _


In [96]:
chessboard(rand_position <- move_one_queen(rand_position))

_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  _  _  _  _  Q  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  _  _  _  _  _  _  Q
_  Q  _  _  _  _  _  _
